#!/bin/sh
status=$(mpc status "%state%" 2>/dev/null)
[ "$status" = "playing" ] || [ "$status" = "paused" ] || exit
artist=$(mpc current "%artist%" 2>/dev/null)
title=$(mpc current "%title%" 2>/dev/null)
[ "$status" = "paused" ] && prefix="⏸ " || prefix="♪ "
printf "%s%s - %s" "$prefix" "$artist" "$title"
